// src/lib/components/app/app-sidebar.svelte
<script lang="ts">
  import * as Sidebar from "$lib/components/ui/sidebar/index.js";
  import type { ComponentProps } from "svelte";

  import House from "@lucide/svelte/icons/house";
  import SquareActivity from "@lucide/svelte/icons/square-activity";
  import Goal from "@lucide/svelte/icons/goal";
  import Landmark from "@lucide/svelte/icons/landmark";
  import Handcoins from "@lucide/svelte/icons/hand-coins";
  import CalendarCheck2 from "@lucide/svelte/icons/calendar-check-2";
  import CirclePoundSterling from "@lucide/svelte/icons/circle-pound-sterling";
  import Settings from "@lucide/svelte/icons/settings";
  import LogOut from "@lucide/svelte/icons/log-out";

  const data = {
    main: [
      {
        title: "Dashboard",
        url: "#",
        icon: House,
      },
      {
        title: "Activity",
        url: "#",
        icon: SquareActivity,
      },
    ],
    user: [
      {
        title: "Accounts",
        url: "#",
        icon: Landmark,
      },
      {
        title: "Goals",
        url: "#",
        icon: Goal,
      },
      {
        title: "Loan",
        url: "#",
        icon: Handcoins,
      },
      {
        title: "Subscriptions",
        url: "#",
        icon: CalendarCheck2,
      },
    ],
    footer: [
      {
        title: "Settings",
        url: "#",
        icon: Settings,
      },
      {
        title: "Logout",
        url: "#",
        icon: LogOut,
      },
    ],
  };
  let { ...restProps }: ComponentProps<typeof Sidebar.Root> = $props();
</script>

<Sidebar.Root collapsible="offcanvas" {...restProps}>
  <Sidebar.Header>
    <Sidebar.Menu>
      <Sidebar.MenuItem>
        <Sidebar.MenuButton class="data-[slot=sidebar-menu-button]:!p-1.5">
          {#snippet child({ props })}
            <a href="##" {...props}>
              <CirclePoundSterling class="!size-5" />
              <span class="text-base font-semibold">Pennywise</span>
            </a>
          {/snippet}
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  </Sidebar.Header>
  <Sidebar.Content>
    <Sidebar.Group>
      <Sidebar.GroupContent class="flex flex-col gap-2">
        <Sidebar.Menu>
          {#each data.main as item (item.title)}
            <Sidebar.MenuItem>
              <Sidebar.MenuButton tooltipContent={item.title}>
                {#snippet child({ props })}
                  <a href={item.url} {...props}>
                    <item.icon />
                    <span>{item.title}</span>
                  </a>
                {/snippet}
              </Sidebar.MenuButton>
            </Sidebar.MenuItem>
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
    <Sidebar.Group>
      <Sidebar.GroupLabel>User</Sidebar.GroupLabel>
      <Sidebar.GroupContent class="flex flex-col gap-2">
        <Sidebar.Menu>
          {#each data.user as item (item.title)}
            <Sidebar.MenuItem>
              <Sidebar.MenuButton tooltipContent={item.title}>
                {#snippet child({ props })}
                  <a href={item.url} {...props}>
                    <item.icon />
                    <span>{item.title}</span>
                  </a>
                {/snippet}
              </Sidebar.MenuButton>
            </Sidebar.MenuItem>
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
  </Sidebar.Content>
  <Sidebar.Footer>
    <Sidebar.Menu>
      {#each data.footer as item (item.title)}
        <Sidebar.MenuItem>
          <Sidebar.MenuButton tooltipContent={item.title}>
            {#snippet child({ props })}
              <a href={item.url} {...props}>
                <item.icon />
                <span>{item.title}</span>
              </a>
            {/snippet}
          </Sidebar.MenuButton>
        </Sidebar.MenuItem>
      {/each}
    </Sidebar.Menu>
  </Sidebar.Footer>
</Sidebar.Root>

// client/src/components/app-sidebar.tsx
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarGroup,
  SidebarGroupContent,
} from "@/components/ui/sidebar";
import { Clock, Landmark, LayoutDashboardIcon, Settings } from "lucide-react";

const data = [
  {
    title: "Dashboard",
    icon: LayoutDashboardIcon,
    url: "/",
  },
  {
    title: "Activity",
    icon: Clock,
    url: "/log",
  },
  {
    title: "Accounts",
    icon: Landmark,
    url: "/accounts",
  },
  {
    title: "Settings",
    icon: Settings,
    url: "/settings",
  },
];

export function AppSidebar({ ...props }: React.ComponentProps<typeof Sidebar>) {
  return (
    <Sidebar collapsible="offcanvas" {...props}>
      <SidebarHeader>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton
              asChild
              className="data-[slot=sidebar-menu-button]:!p-1.5"
            >
              <a href="#">
                <span className="text-base font-semibold">Acme Inc.</span>
              </a>
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarHeader>
      <SidebarContent>
        <SidebarGroup>
          <SidebarGroupContent className="flex flex-col gap-2">
            <SidebarMenu>
              {data.map((item) => (
                <SidebarMenuItem key={item.title}>
                  <SidebarMenuButton asChild tooltip={item.title}>
                    <a href={item.url}>
                      {item.icon && <item.icon />}
                      <span>{item.title}</span>
                    </a>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              ))}
            </SidebarMenu>
          </SidebarGroupContent>
        </SidebarGroup>
      </SidebarContent>
      <SidebarFooter></SidebarFooter>
    </Sidebar>
  );
}
